context:
  name: "valkey"
  version: "6.1.0"

package:
  name: "valkey-py"
  version: "${{ version }}"

source:
  url: https://github.com/valkey-io/valkey-py/archive/refs/tags/v${{ version }}.zip
  sha256: 69ee82e5173a394c88e94390be7ff85d0386205e190060c1d4a7ff7bfeb1be24

build:
  noarch: python
  number: 1
  script:
    env:
      PIP_USE_PEP517: "1"
      PIP_NO_BUILD_ISOLATION: "1"
    content: "python -m pip install ."

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - pip
  run:
    - python >=${{ python_min }}
    - async-timeout >=4.0.3

  # https://github.com/valkey-io/valkey-py/blob/12004ca23f5df5d43326ca600703d26ec2387e9a/setup.py#L59-L61
  run_constraints:
    - libvalkey-py >=4.0.1

    - "cryptography >=36.0.1"
    - "requests >=2.31.0"

    - "pyopenssl >=23.2.1"

tests:
  - python:
      imports:
        - valkey
      python_version: ${{ python_min }}.*

about:
  license: MIT
  license_file:
    - LICENSE
  summary: Valkey Python client based on a fork of redis-py
  homepage: https://github.com/valkey-io/valkey-py
  repository: https://github.com/valkey-io/valkey-py

extra:
  recipe-maintainers:
    - trim21
